[tool.poetry]
package-mode=false

[tool.poetry.dependencies]
python=">=3.12.0,<3.15"
aiogram = "^3.23.0"
pydantic-settings = "^2.12.0"
sqlalchemy = "^2.0.45"
alembic = "^1.17.2"
asyncpg = "^0.31.0"
openai = "^2.13.0"

[dependency-groups]
dev = [
    "black (>=25.12.0,<26.0.0)"
]
